from typing import Tuple

Coord = Tuple[float, float]

CHARACTER_MAP = {
    0x00: "Mario",
    0x01: "Fox",
    0x02: "Captain Falcon",
    0x03: "Donkey Kong",
    0x04: "Kirby",
    0x05: "Bowser",
    0x06: "Link",
    0x07: "Sheik",
    0x08: "Ness",
    0x09: "Peach",
    0x0a: "Popo",
    0x0b: "Nana",
    0x0c: "Pikachu",
    0x0d: "Samus",
    0x0e: "Yoshi",
    0x0f: "Jigglypuff",
    0x10: "Mewtwo",
    0x11: "Luigi",
    0x12: "Marth",
    0x13: "Zelda",
    0x14: "Young Link",
    0x15: "Dr. Mario",
    0x16: "Falco",
    0x17: "Pichu",
    0x18: "Mr. Game & Watch",
    0x19: "Ganondorf",
    0x1a: "Roy",
    0x1d: "WIREFRAME_MALE",
    0x1e: "WIREFRAME_FEMALE",
    0x1f: "GIGA_BOWSER",
    0x20: "SANDBAG",
    0xff: "UNKNOWN_CHARACTER",
}

STAGE_MAP = {
    0x8: "Fountain of Dreams",
    0x12: "Pokémon Stadium",
    0: "Unknown",
    0x1D: "Random",
    0x6: "Yoshi's Story",
    0x1A: "Dream Land",
    0x18: "Battlefield",
    0x19: "Final Destination",
}

UNKNOWN_CHARACTER = 0xff
SPACIES = ["Fox", "Falco"]
SPACIE_METRICS = ["num_jc_shines_per_game", "jc_shine_frames"]

LOGS_DIR = "./logs/"
DEFAULT_LOG_NAME = "slp_replay_scanner.log"
DEFAULT_LOG_DIR = LOGS_DIR + DEFAULT_LOG_NAME
SCANNING_LOG_NAME = "slp_parsing_errors.log"
SCANNING_LOG_DIR = LOGS_DIR + SCANNING_LOG_NAME
PLOT_LOG_NAME = "plot_errors.log"
PLOT_LOG_DIR = LOGS_DIR + PLOT_LOG_NAME
SLP_FILE = ".slp"
GZ_SLP_FILE = ".slp.gz"
ZIP_FILE = ".zip"
SAVE_FILE = ".slpscan"

DASH_DANCE_FRAMES = 3
WAVEDASH_FRAMES = 15
EARLY_AERIAL_FRAMES = 6
CROUCH_UPTILT_FRAMES = 8
PIVOT_FRAMES = 3
PIVOT_LOOKBACK = 12
JC_SHINE_FRAMES = 5
LEDGEDASH_FRAMES = 15
FRAMES_PER_SECOND = SECONDS_PER_MINUTE = MINUTES_PER_HOUR = 60
HOURS_PER_DAY = 24
MIN_STAT_CUTOFF = 5
MIN_ANIMATIONS = 3

MAX_DIGITAL_COORDS = 120
MAX_UNIQUE_DIGITAL_COORDS = 60
MAX_POSSIBLY_DIGITAL_COORDS = 380
MAX_UNIQUE_POSSIBLY_DIGITAL_COORDS = 200
MAX_POSSIBLY_DIGITAL_ENTROPY = 1.89

SMALL_OFF_AXIS_THRESHOLD = 0.08
RIM_COORD_MAX = 432
MAX_RIM_PROP = 0.5
THREE_MINUTES = 3 * FRAMES_PER_SECOND * SECONDS_PER_MINUTE
MIN_ANALOG_RATIO = 0.02
MIN_ANALOG_UNIQUE = 32
DZ_THRESHOLD_COORD = 0.2875
DZ_THRESHOLD = 23
MAX_RAW_THRESHOLD = 80
EPSILON = 0.0125

BINS = 30
SMALL_FONT_SIZE = 10
FONT_SIZE = 12
LARGE_DATASET = 10000
VERY_LARGE_DATASET = 100000
EXTREMELY_LARGE_DATASET = 10000000
TOTAL_DATA_CUTOFF = 5 * (EXTREMELY_LARGE_DATASET + EXTREMELY_LARGE_DATASET)
MAX_HL_ITERATIONS = 100
MAX_CARTESIAN_PRODUCT_SIZE_NAIVE = LARGE_DATASET * LARGE_DATASET
MAX_CARTESIAN_PRODUCT_SIZE = VERY_LARGE_DATASET * VERY_LARGE_DATASET
CARTESIAN_PRODUCT_CUTOFF = VERY_LARGE_DATASET * EXTREMELY_LARGE_DATASET
MAX_BOOTSTRAP_ITERATIONS = 10000
MAX_BOOTSTRAP_ITERATIONS_LARGE = 1000
MIN_BOOTSTRAP_ITERATIONS = 100
DEFAULT_CONFIDENCE = 0.95
NUMERICAL_EPSILON = 1e-9
FIGURE_SIZE = (8, 6)

TARGET_CHUNK_MB = 64
BYTES_PER_MB = 1024 * 1024
TARGET_CHUNK_BYTES = TARGET_CHUNK_MB * BYTES_PER_MB
MIN_CHUNKS_PER_WORKER = 4
MAX_CHUNKS_PER_WORKER = 32
MIN_CHUNKSIZE = 4
MAX_CHUNKSIZE = 64
